pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 9000:9000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'echo "App will be running for 60 seconds"'
                sleep(60)
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deliver'){
            steps{
                script {
                    def deployChoice = input(
                        id: 'deployChoice',
                        message: 'Do you want to deploy this release?',
                        parameters: [
                            booleanParam(defaultValue: true, description: 'Deploy the release', name: 'DEPLOY')
                        ]
                    )
                    if (deployChoice) {
                        echo 'Deploying...'
                    } else {
                        echo 'Not deploying...'
                    }
                }
            }
        }
    }
}
